let users=[{"id":1,"name":"Olag","email":"ovirgoe0@google.com.au","gender":"Male"},
{"id":2,"name":"Tadio","email":"ttreat1@shinystat.com","gender":"Male"},
{"id":3,"name":"Zachary","email":"zmaron2@drupal.org","gender":"Male"},
{"id":4,"name":"Fabien","email":"fkornel3@java.com","gender":"Male"},
{"id":5,"name":"Alasteir","email":"awigmore4@msn.com","gender":"Male"},
{"id":6,"name":"Adrianne","email":"abalden5@google.fr","gender":"Female"},
{"id":7,"name":"Chariot","email":"ckybird6@un.org","gender":"Male"},
{"id":8,"name":"Corney","email":"comara7@themeforest.net","gender":"Male"},
{"id":9,"name":"Babs","email":"bmeron8@marketwatch.com","gender":"Female"},
{"id":10,"name":"Anthony","email":"astiger9@t.co","gender":"Male"},
{"id":11,"name":"Baird","email":"bmarkiea@bloomberg.com","gender":"Male"},
{"id":12,"name":"Cull","email":"ctowerseyb@msn.com","gender":"Agender"},
{"id":13,"name":"Lavena","email":"lsydec@hp.com","gender":"Female"},
{"id":14,"name":"Angelika","email":"ayurocjkind@arizona.edu","gender":"Female"},
{"id":15,"name":"Daphna","email":"dstockhille@yahoo.co.jp","gender":"Female"},
{"id":16,"name":"Cal","email":"coretf@printfriendly.com","gender":"Male"},
{"id":17,"name":"Arthur","email":"arenisong@feedburner.com","gender":"Male"},
{"id":18,"name":"Milt","email":"mdenricoh@bbb.org","gender":"Male"},
{"id":19,"name":"Giuditta","email":"gfrankishi@hatena.ne.jp","gender":"Female"},
{"id":20,"name":"Dell","email":"dbakewellj@guardian.co.uk","gender":"Female"},
{"id":21,"name":"Isa","email":"iklusk@mozilla.org","gender":"Genderqueer"},
{"id":22,"name":"Nerissa","email":"nbadrickl@stanford.edu","gender":"Female"},
{"id":23,"name":"Shalne","email":"sduxburym@hostgator.com","gender":"Polygender"},
{"id":24,"name":"Hirsch","email":"hbrothertonn@boston.com","gender":"Male"},
{"id":25,"name":"Rosella","email":"rortmanno@instagram.com","gender":"Female"},
{"id":26,"name":"Lucias","email":"lbeddardp@is.gd","gender":"Male"},
{"id":27,"name":"Hilly","email":"hnewbornq@nsw.gov.au","gender":"Male"},
{"id":28,"name":"Teodor","email":"twaringr@ihg.com","gender":"Bigender"},
{"id":29,"name":"Clevie","email":"cseywoods@stumbleupon.com","gender":"Male"},
{"id":30,"name":"Shayla","email":"sdecourseyt@thetimes.co.uk","gender":"Female"},
{"id":31,"name":"Andres","email":"atheriotu@hostgator.com","gender":"Male"},
{"id":32,"name":"Juieta","email":"jmatyv@nih.gov","gender":"Non-binary"},
{"id":33,"name":"Emmerich","email":"eeannettaw@oracle.com","gender":"Male"},
{"id":34,"name":"Ardith","email":"aliberox@netvibes.com","gender":"Female"},
{"id":35,"name":"Thebault","email":"tmchaley@princeton.edu","gender":"Male"},
{"id":36,"name":"Hyacintha","email":"hgrenshieldsz@topsy.com","gender":"Female"},
{"id":37,"name":"Dale","email":"dcosson10@yellowbook.com","gender":"Female"},
{"id":38,"name":"Lila","email":"lwaldrum11@weibo.com","gender":"Female"},
{"id":39,"name":"Fabien","email":"fisenor12@businessinsider.com","gender":"Male"},
{"id":40,"name":"Ezmeralda","email":"emellmer13@miitbeian.gov.cn","gender":"Female"},
{"id":41,"name":"Nissy","email":"ndomb14@virginia.edu","gender":"Female"},
{"id":42,"name":"Judie","email":"jsea15@wikimedia.org","gender":"Female"},
{"id":43,"name":"Jamie","email":"jjakes16@qq.com","gender":"Male"},
{"id":44,"name":"Chalmers","email":"ceaseman17@archive.org","gender":"Male"},
{"id":45,"name":"Windham","email":"wkohnen18@hc360.com","gender":"Male"},
{"id":46,"name":"Janka","email":"jgallihawk19@nydailynews.com","gender":"Female"},
{"id":47,"name":"Jobina","email":"jcolgrave1a@mail.ru","gender":"Female"},
{"id":48,"name":"Belle","email":"bcordner1b@marketwatch.com","gender":"Female"},
{"id":49,"name":"Olva","email":"opeacop1c@zimbio.com","gender":"Female"},
{"id":50,"name":"Maximilianus","email":"msleith1d@cbslocal.com","gender":"Male"}]


//print user email ids  or names or ids 

for(user of users){
    //console.log(user.id)
    console.log(user.email)
}